git clone https://github.com/DeveloppeurPascal/LeTempsDUneTomate.git
git clone https://github.com/DeveloppeurPascal/Planning-API.git
git clone https://github.com/DeveloppeurPascal/LogNPass-app.git
git clone https://github.com/DeveloppeurPascal/DProj2WinSetup.git
git clone https://github.com/DeveloppeurPascal/App-Stores-Screen-Captures-Generator.git
git clone https://github.com/DeveloppeurPascal/ExeBulkSigning.git
git clone https://github.com/DeveloppeurPascal/Folder2FMXImageList.git
git clone https://github.com/DeveloppeurPascal/GooglePlayDeveloperBannerGenerator.git
git clone https://github.com/DeveloppeurPascal/PicMobGenerator.git
git clone https://github.com/DeveloppeurPascal/HTML-Writer.git
git clone https://github.com/DeveloppeurPascal/Pic-Resize.git
git clone https://github.com/DeveloppeurPascal/Socket-Messaging-Code-Generator.git
git clone https://github.com/DeveloppeurPascal/SVGFolder2DelphiUnit.git
git clone https://github.com/DeveloppeurPascal/SUTOM_Helper.git
git clone https://github.com/DeveloppeurPascal/Text2HTML.git
git clone https://github.com/DeveloppeurPascal/Video-Cutter.git
git clone https://github.com/DeveloppeurPascal/Video-Merger.git
git clone https://github.com/DeveloppeurPascal/Video-Splitter.git
git clone https://github.com/DeveloppeurPascal/YTVideoSeries.git
git clone https://github.com/DeveloppeurPascal/Zicplay.git
git clone https://github.com/DeveloppeurPascal/Video-Title-Page-Generator.git
git clone https://github.com/DeveloppeurPascal/Spritesheet-Splitter.git
git clone https://github.com/DeveloppeurPascal/Spritesheet-Creator.git
git clone https://github.com/DeveloppeurPascal/Fediverse-GET-URL-Tester.git
git clone https://github.com/DeveloppeurPascal/Fie-Frapic.git
git clone https://github.com/DeveloppeurPascal/XOR-Keys-Generator.git
git clone https://github.com/DeveloppeurPascal/Swap-Keys-Generator.git
git clone https://github.com/DeveloppeurPascal/Shift-Keys-Generator.git
git clone https://github.com/DeveloppeurPascal/IDB-keys-Generator.git
git clone https://github.com/DeveloppeurPascal/CopyrightPascalProjects.git
git clone https://github.com/DeveloppeurPascal/FMX-MultiPad.git
git clone https://github.com/DeveloppeurPascal/FMX-Notepad.git
git clone https://github.com/DeveloppeurPascal/GestionComptesPersonnels.git
git clone https://github.com/DeveloppeurPascal/My-day-in-pictures.git
git clone https://github.com/DeveloppeurPascal/photo-album-generator.git
git clone https://github.com/DeveloppeurPascal/Promo-Verif.git
git clone https://github.com/DeveloppeurPascal/COVID-ContactTracing-RestauBar.git
git clone https://github.com/DeveloppeurPascal/Link-Website-Generator.git
git clone https://github.com/DeveloppeurPascal/GroupProjUpdater.git
